MEME-UMC/MEME_SERVICE

src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
src/main/java/umc/meme/shop/global/ErrorStatus.java
src/main/java/umc/meme/shop/global/SuccessStatus.java
src/main/java/umc/meme/shop/global/exception/GlobalException.java
src/main/java/umc/meme/shop/global/exception/GlobalExceptionAdvice.java
src/main/java/umc/meme/shop/global/exception/GlobalExceptionHandler.java
src/main/java/umc/meme/shop/global/response/ApiResponse.java

#5 
- ApiResponse 통일
- SuccessCode, ErrorCode enum 추가
- Exception Handling 구현
- 임시 응답 테스트 코드 추가

[Add] ApiResponse 통일, Exception handling

---

src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
src/main/java/umc/meme/shop/domain/mypage/controller/MyPageController.java
src/main/java/umc/meme/shop/domain/reservation/controller/ReservationController.java
src/main/java/umc/meme/shop/global/SuccessStatus.java
src/main/java/umc/meme/shop/global/response/ApiResponse.java

#3 
- API 명세서를 기반으로 controller mapping
- success status data set

[Add] controller mapping

---

build.gradle
src/main/java/umc/meme/shop/config/SwaggerConfig.java
src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
src/main/java/umc/meme/shop/domain/mypage/controller/MyPageController.java
src/main/java/umc/meme/shop/domain/reservation/controller/ReservationController.java
src/main/java/umc/meme/shop/global/ErrorStatus.java

#6 Swagger 작성
Swagger를 작성하는 이슈입니다.
SwaggerConfig 작성 완료했구요, Operation 작성 완료 하였습니다.
처음에는 Swagger Annotation 중 ApiResponse, Parameter 까지 다 작성하였는데요, 컨트롤러가 너무 길어져 Operation 만 남겼습니다. 자세한 설명은 노션에 적는걸로 ~

[Add] Swagger 작성

---

src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
src/main/java/umc/meme/shop/domain/artist/dto/response/ArtistDto.java
src/main/java/umc/meme/shop/domain/favorite/repository/FavoriteArtistRepository.java
src/main/java/umc/meme/shop/domain/favorite/repository/FavoritePortfolioRepository.java
src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
src/main/java/umc/meme/shop/domain/model/dto/request/ModelProfileDto.java
src/main/java/umc/meme/shop/domain/model/entity/Model.java
src/main/java/umc/meme/shop/domain/model/service/ModelService.java
src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioDto.java
src/main/java/umc/meme/shop/global/ErrorStatus.java

#11 
- model 프로필 관리/수정
- 관심 아티스트 조회
- 관심 포트폴리오 조회
- artist dto
관심 아티스트 entity를 artist dto로 mapping
- portfolio dto
관심 포트폴리오 entity를 portfolio dto로 mapping

[Feat] Model ver. MyPage 기능 구현

---

src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
src/main/java/umc/meme/shop/domain/artist/entity/Artist.java
src/main/java/umc/meme/shop/domain/artist/service/ArtistService.java
src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
src/main/java/umc/meme/shop/domain/model/service/ModelService.java
src/main/java/umc/meme/shop/domain/portfolio/entity/Portfolio.java
src/main/java/umc/meme/shop/domain/reservation/controller/ReservationController.java
src/main/java/umc/meme/shop/domain/reservation/dto/request/ReservationRequestDto.java
src/main/java/umc/meme/shop/domain/reservation/dto/response/ReservationResponseDto.java
src/main/java/umc/meme/shop/domain/reservation/entity/Reservation.java
src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
src/main/java/umc/meme/shop/global/ErrorStatus.java

#14 
#16 
예약 서비스 개발에 앞서 포트폴리오 생성 기능이 요구되어
포트폴리오 생성 기능 우선 개발
- 포트폴리오 생성 기능 구현
- 예약 생성 기능 구현
- 예약 상태 변경 기능 구현

[Feat] 포트폴리오 생성, 예약 생성, 예약 상태 변경 기능 구현

---

src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
src/main/java/umc/meme/shop/domain/artist/entity/Artist.java
src/main/java/umc/meme/shop/domain/artist/service/ArtistService.java
src/main/java/umc/meme/shop/domain/portfolio/controller/PortfolioController.java
src/main/java/umc/meme/shop/domain/portfolio/service/PortfolioService.java
src/main/java/umc/meme/shop/domain/reservation/controller/ReservationController.java
src/main/java/umc/meme/shop/domain/reservation/dto/response/ReservationResponseDto.java
src/main/java/umc/meme/shop/domain/reservation/repository/ReservationRepository.java
src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java

#18 
#16 
- 예약하기 조회 기능 구현
- ‼️피그마 요소에 따라서 추후 responseDto 변경될 수도 있음
- portfolio, reservation foldering

[Feat] Artist ver. 예약 조회 기능 구현

---

src/main/java/umc/meme/shop/domain/model/service/ModelService.java
src/main/java/umc/meme/shop/domain/portfolio/controller/PortfolioController.java
src/main/java/umc/meme/shop/domain/portfolio/dto/request/CreatePortfolioDto.java
src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioDto.java
src/main/java/umc/meme/shop/domain/portfolio/entity/Portfolio.java
src/main/java/umc/meme/shop/domain/portfolio/repository/PortfolioRepository.java
src/main/java/umc/meme/shop/domain/portfolio/service/PortfolioService.java
src/main/java/umc/meme/shop/domain/reservation/controller/ReservationController.java
src/main/java/umc/meme/shop/domain/reservation/entity/Reservation.java
src/main/java/umc/meme/shop/domain/reservation/repository/ReservationRepository.java
src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java

#14 
포트폴리오 조회,수정,삭제 기능 추가 및 자잘한 버그 수정입니다.

[Feat] Portfolio Service 관련 기능 추가

---

src/main/java/umc/meme/shop/domain/model/entity/Model.java
src/main/java/umc/meme/shop/domain/model/service/ModelService.java
src/main/java/umc/meme/shop/domain/reservation/dto/response/ReservationResponseDto.java
src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
src/test/java/umc/meme/shop/ArtistTest.java

#26 
- Model의 예약 조회 기능에서 `reservationList`를 반환하도록 코드 수정

[Chore] Model ver. 예약 조회 수정

---

src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
src/main/java/umc/meme/shop/domain/artist/dto/request/ArtistProfileDto.java
src/main/java/umc/meme/shop/domain/artist/entity/Artist.java
src/main/java/umc/meme/shop/domain/artist/service/ArtistService.java

[Feat] Artist 프로필 관리/수정 기능 구현

---

src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
src/main/java/umc/meme/shop/domain/artist/entity/Artist.java
src/main/java/umc/meme/shop/domain/artist/service/ArtistService.java
src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
src/main/java/umc/meme/shop/domain/model/entity/Model.java
src/main/java/umc/meme/shop/domain/model/service/ModelService.java
src/main/java/umc/meme/shop/domain/portfolio/service/PortfolioService.java
src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
src/main/java/umc/meme/shop/global/ErrorStatus.java
src/main/java/umc/meme/shop/global/SuccessStatus.java

#34 
- 포트폴리오 조회 수정 -> artist의 PortfolioList 반환
- 관심 아티스트 조회 수정 -> model의 FavoriteArtistList 반환
- 관심 포트폴리오 조회 수정 -> model의 FavoritePortfolioList 반환

[Chore] 포트폴리오, 관심 아티스트, 관심 메이크업 조회 수정

---

src/main/java/umc/meme/shop/domain/artist/dto/response/ArtistDto.java
src/main/java/umc/meme/shop/domain/favorite/repository/FavoriteArtistRepository.java
src/main/java/umc/meme/shop/domain/favorite/repository/FavoritePortfolioRepository.java
src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
src/main/java/umc/meme/shop/domain/model/service/ModelService.java
src/main/java/umc/meme/shop/global/ErrorStatus.java
src/main/java/umc/meme/shop/global/SuccessStatus.java

#36 
- 관심 아티스트 삭제 기능 구현
- 관심 메이크업 삭제 기능 구현
favoriteArtist dto, favoritePortfolio dto를 사용하지 않는 관계로,
modelId, artistId, portfolioId를 받아 repository에서 조회
favoriteArtist Entity, favoritePortfolio Entity delete

[Feat] 관심 아티스트, 관심 메이크업 삭제 기능 구현

---

src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioDto.java
src/main/java/umc/meme/shop/domain/portfolio/entity/Portfolio.java
src/main/java/umc/meme/shop/domain/reservation/entity/Reservation.java
src/main/java/umc/meme/shop/domain/reservation/repository/ReservationRepository.java
src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
src/main/java/umc/meme/shop/domain/review/dto/response/ReviewResponseDto.java
src/main/java/umc/meme/shop/domain/review/service/ReviewService.java
src/main/java/umc/meme/shop/global/ErrorStatus.java

#28 
- 포트폴리오 - 예약 연관관계 수정
- 예약 관련 예외처리 추가
- 포트폴리오 조회 시 리뷰 리스트 반환
- 포트폴리오 dto 별점 평균 추가(string, 소수 2자리)

[Fix] 포트폴리오, 예약 연관관계 수정 / 예외처리 추가

---

src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
src/main/java/umc/meme/shop/domain/artist/dto/response/ArtistDto.java
src/main/java/umc/meme/shop/domain/artist/entity/Artist.java
src/main/java/umc/meme/shop/domain/artist/entity/enums/Region.java
src/main/java/umc/meme/shop/domain/artist/service/ArtistService.java
src/main/java/umc/meme/shop/domain/portfolio/entity/enums/Category.java
src/test/java/umc/meme/shop/ArtistTest.java

closed #32 
- Artist Entity의 `List<Region>`, `List<Category>` 타입 변경 -> **`List<String>`**
- **`@ElementCollection`** annotation 추가 -> `artist_region`, `artist_specialization` table 추가
- Region, Category enum에 String **Value** 추가
- ArtistDto: List<Region>, List<Category> ->  List<String>으로 변경
- Artist entity: region/category -> string 으로 변환하는 함수 추가
- `@ElementCollection`을 추가하면 해당 엔티티에 종속되는 table이 생성됨 -> 컬렉션 필드에 사용

[Fix] Enum List List<String>으로 변경

---

src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
src/main/java/umc/meme/shop/domain/artist/service/ArtistService.java
src/main/java/umc/meme/shop/global/SuccessStatus.java

closed #25 
- 아티스트 프로필 조회 기능 구현
- 포트폴리오 리스트, 리뷰 리스트 포함

[Feat] 아티스트 프로필 조회 기능 구현

---

src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
src/main/java/umc/meme/shop/global/ErrorStatus.java

[Add] 예약상태변경 예외처리

---

src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
src/main/java/umc/meme/shop/domain/artist/dto/request/ArtistProfileDto.java
src/main/java/umc/meme/shop/domain/artist/service/ArtistService.java
src/main/java/umc/meme/shop/domain/favorite/dto/request/FavoriteArtistDto.java
src/main/java/umc/meme/shop/domain/favorite/dto/request/FavoritePortfolioDto.java
src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
src/main/java/umc/meme/shop/domain/model/dto/request/ModelProfileDto.java
src/main/java/umc/meme/shop/domain/model/service/ModelService.java
src/main/java/umc/meme/shop/domain/portfolio/controller/PortfolioController.java
src/main/java/umc/meme/shop/domain/portfolio/dto/request/CreatePortfolioDto.java
src/main/java/umc/meme/shop/domain/portfolio/dto/request/UpdatePortfolioDto.java
src/main/java/umc/meme/shop/domain/portfolio/service/PortfolioService.java
src/main/java/umc/meme/shop/domain/reservation/controller/ReservationController.java
src/main/java/umc/meme/shop/domain/reservation/dto/request/AlterReservationDto.java
src/main/java/umc/meme/shop/domain/reservation/dto/response/ReservationResponseDto.java
src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
src/main/java/umc/meme/shop/domain/review/controller/ReviewController.java
src/main/java/umc/meme/shop/domain/review/dto/request/ReviewDto.java
src/main/java/umc/meme/shop/domain/review/dto/request/UpdateReviewDto.java
src/main/java/umc/meme/shop/domain/review/service/ReviewService.java

closed #52 
- get 요청을 제외한 path variable 제거
- request dto에 필요한 id 추가
- 서비스 관련 테스트 실행

[Chore] Request Dto 통일

---

src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
src/main/java/umc/meme/shop/domain/model/service/ModelService.java
src/main/java/umc/meme/shop/domain/portfolio/controller/PortfolioController.java
src/main/java/umc/meme/shop/domain/portfolio/converter/PortfolioConverter.java
src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioPageDto.java
src/main/java/umc/meme/shop/domain/portfolio/repository/PortfolioRepository.java
src/main/java/umc/meme/shop/domain/portfolio/service/PortfolioService.java

closed #54 
- `portfolio Converter` 생성
- `favoritePortfolioPageConverter`
- `portfolioPageConverter`
- 포트폴리오 전체 조회 페이징 기능 구현
- 관심 메이크업 조회 페이징 기능 구현
- 카테고리 검색 페이징 기능 구현
- ‼️ 정렬 조건 추가 필요

[Feat] Portfolio Paging 기능 구현

---

src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
src/main/java/umc/meme/shop/domain/model/service/ModelService.java
src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioDto.java
src/main/java/umc/meme/shop/domain/portfolio/entity/Portfolio.java
src/main/java/umc/meme/shop/domain/portfolio/repository/PortfolioRepository.java
src/main/java/umc/meme/shop/domain/portfolio/service/PortfolioService.java
src/main/java/umc/meme/shop/domain/reservation/dto/response/ReservationResponseDto.java
src/main/java/umc/meme/shop/domain/review/service/ReviewService.java
src/main/java/umc/meme/shop/global/ErrorStatus.java

#57 
- 관심 아티스트로 포트폴리오 검색 기능 구현
- 검색 정렬 기능 구현
- 리뷰 순
- 가격 높은 순
- 가격 낮은 순 
- 포트폴리오 필드 수정 -> 별점 평균 추가
- 포트폴리오 dto 별점 평균 계산 로직 제거

[Feat] 관심 아티스트로 포트폴리오 검색 기능 구현/ 검색 정렬 기능 구현

---

src/main/java/umc/meme/shop/domain/artist/dto/response/ArtistDto.java
src/main/java/umc/meme/shop/domain/model/service/ModelService.java
src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioDto.java
src/main/java/umc/meme/shop/domain/review/controller/ReviewController.java
src/main/java/umc/meme/shop/domain/review/service/ReviewService.java

#62 
- 포트폴리오와 리뷰 리스트 분리
- dto 세부 필드 수정

[Chore] 포트폴리오, 리뷰 리스트 분리

---

src/main/java/umc/meme/shop/domain/review/controller/ReviewController.java
src/main/java/umc/meme/shop/domain/review/dto/request/DeleteReviewDto.java
src/main/java/umc/meme/shop/domain/review/entity/Review.java
src/main/java/umc/meme/shop/domain/review/service/ReviewService.java
src/main/java/umc/meme/shop/global/ErrorStatus.java
src/main/java/umc/meme/shop/global/SuccessStatus.java

[Feat] 리뷰 삭제 기능 구현

---

src/main/java/umc/meme/shop/domain/artist/entity/Artist.java
src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioDto.java
src/main/java/umc/meme/shop/domain/portfolio/entity/Portfolio.java

[Add] 포트폴리오 이미지 완료

---

src/main/java/umc/meme/shop/domain/review/dto/response/ReviewListResponseDto.java
src/main/java/umc/meme/shop/domain/review/service/ReviewService.java

[Feat] 별점 현황 map 구현

---

src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioDto.java
src/main/java/umc/meme/shop/domain/portfolio/service/PortfolioService.java
src/main/java/umc/meme/shop/domain/review/dto/request/ReviewDto.java
src/main/java/umc/meme/shop/domain/review/dto/response/ReviewResponseDto.java
src/main/java/umc/meme/shop/domain/review/entity/Review.java
src/main/java/umc/meme/shop/domain/review/entity/ReviewImg.java
src/main/java/umc/meme/shop/domain/review/service/ReviewService.java

closed #56 
[Add]review Img 완료

[Add]review Img 완료

---

src/main/java/umc/meme/shop/domain/portfolio/dto/request/UpdatePortfolioDto.java
src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioDto.java
src/main/java/umc/meme/shop/domain/portfolio/entity/Portfolio.java
src/main/java/umc/meme/shop/domain/portfolio/service/PortfolioService.java
src/main/java/umc/meme/shop/global/ErrorStatus.java

#70 
- 포트폴리오 상세 조회: isblock = true 인 포트폴리오면 Exception
- 포트폴리오 전체 조회 : isblock = true 인 포트폴리오 리스트에서 제거
- Portfolio, PortfolioDto 에서 isblock type이 달라 오류 발생
- boolean & Boolean

[Chore] isBlock인 포트폴리오 숨김 처리

---

src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
src/main/java/umc/meme/shop/domain/model/service/ModelService.java
src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioDto.java
src/main/java/umc/meme/shop/domain/portfolio/repository/PortfolioRepository.java
src/main/java/umc/meme/shop/domain/review/dto/response/ReviewImgDto.java
src/main/java/umc/meme/shop/global/ErrorStatus.java
src/main/java/umc/meme/shop/global/config/SwaggerConfig.java
src/test/java/umc/meme/shop/ArtistTest.java

#75 
- 검색어로 메이크업 기능 구현
- 제목 혹은 내용에 검색어가 포함되면 해당 포트폴리오 리턴
- 최근 검색어로 메이크업 기능 구현
querydsl 공부 더 해서 리팩토링 ~

[Feat] 최근 검색어/ 검색어로 메이크업 검색 기능 구현

---

src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
src/main/java/umc/meme/shop/domain/model/service/ModelService.java
src/main/java/umc/meme/shop/domain/portfolio/repository/PortfolioRepository.java
src/main/java/umc/meme/shop/domain/reservation/controller/ReservationController.java
src/main/java/umc/meme/shop/domain/reservation/dto/request/ReservationRequestDto.java
src/main/java/umc/meme/shop/domain/reservation/dto/response/ReservationCompleteDto.java
src/main/java/umc/meme/shop/domain/reservation/entity/Reservation.java
src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java

#82
- 예약 완료 dto 추가
- isblock = false 인 포트폴리오만 조회하도록 쿼리 추가
- 메이크업 전체 조회 기능 추가

[Chore] 예약 완료 dto 추가 / 포트폴리오 조회 로직 수정

---

src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioDto.java
src/main/java/umc/meme/shop/domain/reservation/controller/ReservationController.java
src/main/java/umc/meme/shop/domain/reservation/dto/response/ArtistLocationDto.java
src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
src/main/java/umc/meme/shop/global/SuccessStatus.java

#84 
- 아티스트 예약 가능 장소 조회 기능 추가
- `makeUpLocation`(VISIT, SHOP, BOTH) / 샵 위치 / 활동 가능 구역 반환 
- 포트폴리오 dto 수정 -> 장소 추가

[Add] 아티스트 예약 가능 장소 설정 기능 추가

---

src/main/java/umc/meme/shop/domain/artist/converter/ArtistConverter.java
src/main/java/umc/meme/shop/domain/favorite/dto/response/FavoriteArtistPageResponseDto.java
src/main/java/umc/meme/shop/domain/favorite/dto/response/FavoriteArtistResponseDto.java
src/main/java/umc/meme/shop/domain/favorite/dto/response/FavoritePortfolioResponseDto.java
src/main/java/umc/meme/shop/domain/favorite/dto/response/FavoritePortfolioResponsePageDto.java
src/main/java/umc/meme/shop/domain/model/service/ModelService.java
src/main/java/umc/meme/shop/domain/portfolio/converter/PortfolioConverter.java

[Add] 관심 포트폴리오/아티스트 dto

---

src/main/java/umc/meme/shop/domain/artist/converter/ArtistConverter.java
src/main/java/umc/meme/shop/domain/artist/dto/response/ArtistDto.java
src/main/java/umc/meme/shop/domain/artist/entity/Artist.java
src/main/java/umc/meme/shop/domain/favorite/dto/response/FavoriteArtistResponseDto.java
src/main/java/umc/meme/shop/domain/favorite/entity/FavoriteArtist.java
src/main/java/umc/meme/shop/domain/favorite/entity/FavoritePortfolio.java
src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
src/main/java/umc/meme/shop/domain/model/entity/Model.java
src/main/java/umc/meme/shop/domain/model/service/ModelService.java
src/main/java/umc/meme/shop/domain/mypage/controller/MyPageController.java
src/main/java/umc/meme/shop/domain/mypage/service/MypageService.java
src/main/java/umc/meme/shop/domain/portfolio/entity/Portfolio.java
src/main/java/umc/meme/shop/domain/reservation/entity/Reservation.java
src/main/java/umc/meme/shop/domain/reservation/repository/ReservationRepository.java
src/main/java/umc/meme/shop/domain/review/entity/Review.java
src/main/java/umc/meme/shop/domain/user/User.java
src/main/java/umc/meme/shop/domain/user/UserRepository.java
src/main/java/umc/meme/shop/global/ErrorStatus.java

[Chore] User entity 생성 / 유저 상속 관계 설정

---

src/main/java/umc/meme/shop/domain/mypage/controller/MyPageController.java
src/main/java/umc/meme/shop/domain/mypage/dto/request/MypageInquiryDto.java
src/main/java/umc/meme/shop/domain/mypage/entity/Inquiry.java
src/main/java/umc/meme/shop/domain/mypage/repository/InquiryRepository.java
src/main/java/umc/meme/shop/domain/mypage/service/MypageService.java
src/main/java/umc/meme/shop/global/ErrorStatus.java
src/main/java/umc/meme/shop/global/SuccessStatus.java

[Add] 문의하기

---

.github/workflows/docker.yml

[CI] CI/CD

---

src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
src/main/java/umc/meme/shop/domain/common/BaseEntity.java
src/main/java/umc/meme/shop/domain/favorite/entity/FavoriteArtist.java
src/main/java/umc/meme/shop/domain/favorite/entity/FavoritePortfolio.java
src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
src/main/java/umc/meme/shop/domain/mypage/entity/Inquiry.java
src/main/java/umc/meme/shop/domain/portfolio/entity/Portfolio.java
src/main/java/umc/meme/shop/domain/portfolio/entity/PortfolioImg.java
src/main/java/umc/meme/shop/domain/reservation/entity/Reservation.java
src/main/java/umc/meme/shop/domain/reservation/repository/ReservationRepository.java
src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
src/main/java/umc/meme/shop/domain/review/entity/Review.java
src/main/java/umc/meme/shop/domain/review/entity/ReviewImg.java
src/main/java/umc/meme/shop/domain/review/service/ReviewService.java
src/main/java/umc/meme/shop/domain/user/User.java
src/main/java/umc/meme/shop/global/ErrorStatus.java

#102 
- BaseEntity 추가
- 예약 중복 예외 처리 추가

[Add ] BaseEntity 추가 / 예약 중복 예외 처리

---

src/main/java/umc/meme/shop/domain/favorite/entity/FavoriteArtist.java
src/main/java/umc/meme/shop/domain/favorite/entity/FavoritePortfolio.java
src/main/java/umc/meme/shop/domain/model/service/ModelService.java
src/main/java/umc/meme/shop/domain/mypage/controller/MyPageController.java
src/main/java/umc/meme/shop/domain/mypage/dto/response/MypageDetailDto.java
src/main/java/umc/meme/shop/domain/mypage/entity/Inquiry.java
src/main/java/umc/meme/shop/domain/mypage/service/MypageService.java
src/main/java/umc/meme/shop/domain/portfolio/entity/Portfolio.java
src/main/java/umc/meme/shop/domain/portfolio/service/PortfolioService.java
src/main/java/umc/meme/shop/domain/reservation/dto/response/ArtistLocationDto.java
src/main/java/umc/meme/shop/domain/reservation/dto/response/ReservationCompleteDto.java
src/main/java/umc/meme/shop/domain/reservation/entity/Reservation.java
src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
src/main/java/umc/meme/shop/domain/review/entity/Review.java
src/main/java/umc/meme/shop/domain/review/service/ReviewService.java
src/main/java/umc/meme/shop/domain/user/UserRepository.java

[Refactor] builder 패턴 일괄 적용

---

src/main/java/umc/meme/shop/domain/model/service/ModelService.java
src/main/java/umc/meme/shop/domain/mypage/dto/response/MypageInquiryResponseDto.java
src/main/java/umc/meme/shop/domain/portfolio/controller/PortfolioController.java
src/main/java/umc/meme/shop/domain/portfolio/repository/PortfolioRepository.java
src/main/java/umc/meme/shop/domain/portfolio/service/PortfolioService.java
src/main/java/umc/meme/shop/domain/review/controller/ReviewController.java
src/main/java/umc/meme/shop/domain/review/repository/ReviewRepository.java
src/main/java/umc/meme/shop/domain/review/service/ReviewService.java

#105 
페이징 처리 로직 수정
- Pageable 객체 자체를 받으면 JPA가 알아서 offset을 계산해줌 !
- @PageDefault 를 통해 Pageable 객체에 담길 내용 기본값 설정 가능

[Fix] 페이징 처리 로직 수정

---

src/main/java/umc/meme/shop/domain/portfolio/controller/PortfolioController.java
src/main/java/umc/meme/shop/domain/portfolio/dto/request/UpdatePortfolioDto.java
src/main/java/umc/meme/shop/domain/portfolio/entity/Portfolio.java
src/main/java/umc/meme/shop/domain/portfolio/entity/PortfolioImg.java
src/main/java/umc/meme/shop/domain/portfolio/service/PortfolioService.java
src/main/java/umc/meme/shop/domain/review/controller/ReviewController.java
src/main/java/umc/meme/shop/domain/review/entity/Review.java
src/main/java/umc/meme/shop/domain/review/entity/ReviewImg.java
src/main/java/umc/meme/shop/domain/review/repository/ReviewRepository.java
src/main/java/umc/meme/shop/domain/review/service/ReviewService.java
src/main/java/umc/meme/shop/global/ErrorStatus.java

#107 
- #107의 이슈 수정
- 포트폴리오 수정/삭제 시, 포트폴리오 이미지 여러장 처리할 수 있도록 해당 부분 수정
- 정상 작동 확인 완료 !!

[Fix] ReviewImg, PortfolioImg 관련 로직 수정

---

src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
src/main/java/umc/meme/shop/domain/artist/dto/request/ArtistProfileDetailDto.java
src/main/java/umc/meme/shop/domain/artist/dto/response/ArtistDto.java
src/main/java/umc/meme/shop/domain/artist/service/ArtistService.java
src/main/java/umc/meme/shop/domain/model/service/ModelService.java
src/main/java/umc/meme/shop/domain/portfolio/controller/PortfolioController.java
src/main/java/umc/meme/shop/domain/portfolio/dto/request/PortfolioDetailRequestDto.java
src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioDetailDto.java
src/main/java/umc/meme/shop/domain/portfolio/service/PortfolioService.java
src/main/java/umc/meme/shop/domain/reservation/controller/ReservationController.java
src/main/java/umc/meme/shop/global/ErrorStatus.java
src/main/java/umc/meme/shop/global/enums/WorkExperience.java

#113 
- 포트폴리오 조회, 아티스트 프로필 조회 request dto 추가

[Chore] 관심 포트폴리오, 관심 아티스트 설정 여부 리턴

---

src/main/java/umc/meme/shop/domain/model/controller/ModelController.java

[FIX] 메이크업 검색 기능 오류

---

src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioDetailDto.java
src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioDto.java
src/main/java/umc/meme/shop/domain/portfolio/dto/response/PortfolioPageDto.java

[Add] 포트폴리오 조회시, userId

---

src/main/java/umc/meme/shop/domain/user/User.java

add : User 엔티티에 details 추가

---

src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
src/main/java/umc/meme/shop/domain/mypage/controller/MyPageController.java
src/main/java/umc/meme/shop/domain/portfolio/controller/PortfolioController.java
src/main/java/umc/meme/shop/domain/reservation/controller/ReservationController.java
src/main/java/umc/meme/shop/domain/reservation/entity/Reservation.java
src/main/java/umc/meme/shop/domain/review/controller/ReviewController.java
src/main/java/umc/meme/shop/domain/review/dto/response/ReviewAvailableListResponseDto.java
src/main/java/umc/meme/shop/domain/review/service/ReviewService.java
src/main/java/umc/meme/shop/global/SuccessStatus.java

#124 
- 리뷰 작성 가능한 예약 리스트 조회 기능 구현
- `Reservation.status == Status.COMPLETE` 이 아니면 리스트에서 제거
- `Reservation.isReview == true` 면 리스트에서 제거
🚨 NestedServletException - Name for argument type [java.lang.Long] not available 
➡️ Pathvariable의 name 명시 추가

[Feat] 리뷰 작성 가능 예약 리스트 조회기능 구현

---

src/main/java/umc/meme/shop/domain/artist/dto/request/ArtistProfileDto.java
src/main/java/umc/meme/shop/domain/artist/dto/request/AvailableTimeRequestDto.java
src/main/java/umc/meme/shop/domain/artist/dto/response/ArtistDto.java
src/main/java/umc/meme/shop/domain/artist/dto/response/AvailableTimeDto.java
src/main/java/umc/meme/shop/domain/artist/entity/Artist.java
src/main/java/umc/meme/shop/domain/artist/entity/AvailableTime.java
src/main/java/umc/meme/shop/domain/artist/repository/AvailableTimeRepository.java
src/main/java/umc/meme/shop/domain/artist/service/ArtistService.java
src/main/java/umc/meme/shop/domain/portfolio/controller/PortfolioController.java
src/main/java/umc/meme/shop/domain/reservation/dto/request/ReservationRequestDto.java
src/main/java/umc/meme/shop/domain/reservation/dto/response/ReservationCompleteDto.java
src/main/java/umc/meme/shop/domain/reservation/dto/response/ReservationResponseDto.java
src/main/java/umc/meme/shop/domain/reservation/entity/Reservation.java
src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
src/main/java/umc/meme/shop/domain/review/dto/response/ReviewAvailableListResponseDto.java
src/main/java/umc/meme/shop/global/ErrorStatus.java

#127 
- `Map<DayOfWeek, Times>` 분리 후 `AvailableTime entity` 생성
- AvailableTime : Artist 연관관계 설정
- 예약된 시간은 `isReserved = true` 로 설정
- 예약 가능 시간 조회 수정 -> 예약된 시간은 리스트에서 제외
- 예약하기 RequestDto 수정 -> 예외처리 로직 수정

[Chore] AvailableTime entity 생성 / 예약 가능 시간 조회 시 이미 예약된 시간 제외

---

src/main/java/umc/meme/shop/domain/artist/entity/AvailableTime.java
src/main/java/umc/meme/shop/domain/reservation/dto/response/ReservationCompleteDto.java
src/main/java/umc/meme/shop/domain/reservation/dto/response/ReservationResponseDto.java
src/main/java/umc/meme/shop/domain/reservation/entity/Reservation.java
src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
src/main/java/umc/meme/shop/domain/review/dto/response/ReviewAvailableListResponseDto.java

#129 
- Reservation, AvailableTime entity 1:1 연관관계 설정
- Reservation 관련 Dto 필드 수정
- 예약 상태 변경(EXPECTED -> CANCEL)
- `availableTime.isReservated = false`
- `reservation entity delete`

[Refactor] Reservation, AvailableTime entity 연관관계 설정

---

src/main/java/umc/meme/shop/domain/reservation/controller/ReservationController.java
src/main/java/umc/meme/shop/domain/reservation/dto/response/ArtistReservationDetailDto.java
src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
src/main/java/umc/meme/shop/global/SuccessStatus.java

#132 
- Artist ver. 예약 상세 조회 기능 구현

[Feat] Artist ver. 예약 상세 조회 기능 구현

---

src/main/java/umc/meme/shop/domain/reservation/controller/ReservationController.java
src/main/java/umc/meme/shop/domain/reservation/dto/response/ModelReservationDetailDto.java
src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java

#133 
- Model ver. 예약 상세 조회 기능 구현
- 🚨포트폴리오 id 반환 여부 논의 필요

[Feat] Model ver. 예약 상세 조회 기능 구현

---

src/main/java/umc/meme/shop/domain/review/controller/ReviewController.java
src/main/java/umc/meme/shop/domain/review/dto/response/MyReviewResponseDto.java
src/main/java/umc/meme/shop/domain/review/dto/response/ReviewAvailableListDto.java
src/main/java/umc/meme/shop/domain/review/dto/response/ReviewDetailsDto.java
src/main/java/umc/meme/shop/domain/review/dto/response/ReviewResponseDto.java
src/main/java/umc/meme/shop/domain/review/service/ReviewService.java
src/main/java/umc/meme/shop/global/SuccessStatus.java

closed #136 
- 리뷰 세부 조회 API 구현
- 리뷰 작성 가능 예약리스트 조회 필드 수정
- DayOfWeek, Times 제거
- portfolioImg 추가 
- 리뷰 리스트 조회 필드 수정
- 리뷰 생성 날짜 / 리뷰Id / model 프로필 이미지 추가
- 내가 쓴 리뷰 리스트 조회 dto 생성

[Chore] Review 관련 세부 사항 수정

---

src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
src/main/java/umc/meme/shop/domain/model/controller/ModelController.java
src/main/java/umc/meme/shop/domain/mypage/controller/MyPageController.java
src/main/java/umc/meme/shop/domain/portfolio/controller/PortfolioController.java
src/main/java/umc/meme/shop/domain/reservation/controller/ReservationController.java
src/main/java/umc/meme/shop/domain/reservation/dto/response/ArtistReservationDetailDto.java
src/main/java/umc/meme/shop/domain/reservation/dto/response/ModelReservationDetailDto.java
src/main/java/umc/meme/shop/domain/reservation/service/ReservationService.java
src/main/java/umc/meme/shop/domain/review/controller/ReviewController.java
src/main/java/umc/meme/shop/domain/review/dto/response/MyReviewResponseDto.java
src/main/java/umc/meme/shop/domain/review/dto/response/ReviewAvailableListDto.java
src/main/java/umc/meme/shop/domain/review/dto/response/ReviewDetailsDto.java
src/main/java/umc/meme/shop/domain/review/service/ReviewService.java
src/main/java/umc/meme/shop/global/SuccessStatus.java

#136 
- DevCon ver. Review, Reservation 수정
- 아티스트, 모델 예약 상세 조회 기능 구현
- 리뷰 작성 가능 예약리스트 조회 기능 구현
- 리뷰 상세 조회 기능 구현
- 내가 쓴 리뷰 리스트 Response field 수정

[Chore] Reservation, Review 상세 정보 수정

---

src/main/java/umc/meme/shop/domain/artist/controller/ArtistController.java
src/main/java/umc/meme/shop/domain/artist/dto/request/ArtistProfileDto.java
src/main/java/umc/meme/shop/domain/artist/dto/request/AvailableTimeRequestDto.java
src/main/java/umc/meme/shop/domain/artist/dto/response/ArtistDto.java
src/main/java/umc/meme/shop/domain/artist/entity/Artist.java
src/main/java/umc/meme/shop/domain/artist/entity/AvailableTime.java
src/main/java/umc/meme/shop/domain/artist/service/ArtistService.java
src/main/java/umc/meme/shop/global/SuccessStatus.java

closed #140 
- 아티스트 예약 가능 시간 편집 API 분리
- Request Dto 생성 및 수정
- AvailableTimeDto 분리
- `peek()`

[Refactor] 아티스트 예약 가능 시간 편집 API 분리

---

src/main/java/umc/meme/shop/domain/artist/entity/Artist.java

#146 
fix: Artist - tempMethod에 workExperience 설정 내용 추가

fix: Artist - tempMethod에 workExperience 설정 내용 추가
